### PR TITLE
Dropping support for Phase 1 / 2 rendering (including CM5 / Terminus V1 content) and improving PL experience

### PR DESCRIPTION
**Pull request by colingourlay**
This is a big one 😅

It's not super obvious from looking at the diff what the scope of the changes are, so I'm going to group/distil them from my commit messages...

## Updated app initialisation

- Execution stops immediately on non-PL website generations. We'll continue using the current major version of Odyssey on stories that need to run on Phase 1 / Phase 2, until we (or DSI & CPH) find the time to port them over.
- The bulk of the app is now in a 2nd build target called app.js so that pre-requisite tasks can run ASAP.
- The index.js build target is now a tiny kick-start that provides polyfills, manages page unveiling and is responsible for performing 3 asynchronous tasks before running the app:
  1. Importing the app module,
  2. Fetching the article's terminus document and
  3. Obtaining a permit from PL to modify the DOM

## Simplified interaction with Terminus documents

- terminus-fetch will always use v2 (the default), as we don't need to fetch from P1/P2 articles
- Cache terminus fetch requests by key so documents are only fetched once.
- Deep freeze terminus response objects so they can't be modified by accident
- Image asset lookup (mainly for Pictures) could be greatly simplified now that we only have one format of URL to consult (no more CM5 content) and everything has a binaryKey.
- As well as keeping a record of images defined in the article terminus document, we now keep a record of all 'embedded' media. We now have an additional document fetching utility that will consult this record first, in case it can save a network round trip.
- Consolidate all usage of terminus-fetch to its promise-based API, so we no longer have a mix of promises and callbacks in the codebase

## Simplified page reset & takeover

- DOM selectors that were used to find elements in Phase 1 / 2 are gone: share links, bylines, info sources, WYSIWYG teasers (block|pull-)quotes, primary media, related stories, image embeds, video embeds
- Remove reset steps and styles that didn't apply to PL DOMs
- Remove font loading/definitions as PL already loads ABC Serif and ABC Sans Nova (under the same "ABCSans" name)
- Remove associated JS takeover hacks for P1's news-core
- The order of later transforms has been tweaked so that those that impact the bottom of the page can be performed last
- Remove everything related to the `nucwed` preview site (iframe restyling, debug DOM removal, 
- Assume meta.isPL is always true, removing conditionals that consulted it, but leave it there (set to true) until we can be sure stories/plugins no longer depend on it
- Pre-emptively fetch embedded teaser targets, as they will almost certainly be requested later when building things like video players from (Video) Teaser documents
- Patch-up PL byline parsing to remove preview site author document tooltips
- Phase 1 / 2 component transform parsing logic has been removed from pictures, videos, captions, quotes & story teasers

## Updates to Odyssey components

- Component styles are now injected lazily as needed, ensuring correct order and avoiding needless layout thrashing
- The Picture component has been overhauled with an opt-out lazy loader, so that we can show Header images instantly (no needless jarring fade-in). This can (eventually) be replaced with native browser lazy-loading once Safari turns on its support by default.
- Now that there are no more CORS issues on the PL preview site, we can remove Picture's preview-only manual image source management and let the picture/source elements do the heavy lifting everywhere, as well as re-enable blurring (during lazy loading) on PL
- Use the new document lookup utility for the VideoPlayer, Recirculation and WhatsNext components, to try to avoid terminus network round trips
- We can count on WYSIWYG teasers being correctly formatted now, so the util-dewysiwyg library has been removed
- Clean-up in the Block component to improve readibility of the transitionable media implementation (the in-built scrollyteller)
- Removed HTML Fragment (init-interactive) media source capability from Header
- Refactored video poster and source selection

## Removal of PL React components ("async-components")

- A new vanilla InteractiveEmbed component has been created to replace the PL Interactive component (to support things like dynamic Tweets and FB posts that died as the decoy came online)
- The PL Nav component is gone (this was injected into Phase 1 pages)
- Now that there are no more PL React components, that entire solution is removed
- The aunty project type has reverted from 'react' to 'basic' and a bunch of dependencies removed

## Miscellaneous

- Replace the package that handles HTML templating (bel) with nanohtml, which does the exact same thing, but can now be performed at build time (a la Svelte) rather than bundling the parser and executing it in the browser
- Improve the PL Sidebar component selector so that post-story recirculation content isn't removed by accident
- Remove support (and warning logs) for usage of old markers and scrollytellers, as PL stories don't contain them
- Remove GalleryEmbed component and transform (we can restore this once PL releases support for this and we decide that this is a preferable way of building galleries/mosaics to the stack of image embeds we currently have)
- The WhatNext component can assume the browser supports CSS grid, so we no longer check for support
- Remove trim util, as we can rely on String#trim
- Lots of code clean-up, thanks to stuff pointed out by VS Code (unused imports, arguments, etc.)
- Re-organise src directory so that all app-related modules are inside the app directory

### CODE REVIEW

**Review by phocks — APPROVED** [review]
Damn that's a big PR you were right @colingourlay

Looks good if it works it works!

**Comment by colingourlay** [comment]
> Looks good if it works it works!

😂

**Comment by colingourlay** [comment]
Here are some stories you can check out the latest `drop-p1-p1-support` branch deployment on (and compare to latest versioned `main`)...

- [Kitchen Sink (`main` / `#6.1.1`)](https://master-news-web.news-web-developer.presentation-layer.abc-prod.net.au/news/2022-08-12/kitchen-sink/101160796?terminusBaseURL=https://api-preview.private.terminus.abc-prod.net.au/api/v2)
- [Kitchen Sink (`drop-p1-p1-support.0`)](https://master-news-web.news-web-developer.presentation-layer.abc-prod.net.au/news/2022-08-16/kitchen-sink-drop-p1-p2-support/101336866?terminusBaseURL=https://api-preview.private.terminus.abc-prod.net.au/api/v2)
- [Interactive View Types (`main` / `#6.1.1`)](https://master-news-web.news-web-developer.presentation-layer.abc-prod.net.au/news/2022-08-16/interactive-view-types/100668672?terminusBaseURL=https://api-preview.private.terminus.abc-prod.net.au/api/v2)
- [Interactive View Types (`drop-p1-p1-support.0`)](https://master-news-web.news-web-developer.presentation-layer.abc-prod.net.au/news/2022-08-16/interactive-view-types-drop-p1-p2-support/101336858?terminusBaseURL=https://api-preview.private.terminus.abc-prod.net.au/api/v2)

**Review by jtfell — APPROVED** [review]
This all looks good to me @colingourlay! The previews look identical, the code seems *much* simpler (although I'm not familiar enough with the codebase to have much insight into that)

Overall, smaller bundle size and a step towards making the port to PL easier is a great outcome. Awesome work!

**Review by drzax — APPROVED** [review]

**Comment by drzax** [comment]
@colingourlay I think you might have somehow accidentally also merged this into the `legacy` branch, which I assume is supposed to retain support for P1?

**Comment by colingourlay** [comment]
@drzax I'm assuming this happened because there were no unique commits on the `legacy` branch, so it pointed to the same commit that `main` did at the time, and the merge updated the HEAD of both branches. I've nuked the original `legacy` branch and re-created it at the last pre-merge commit.

**Pull request merged**
