### PR TITLE
Support takeover of stories rendered by Presentation Layer

### PR DESCRIPTION
**Pull request by colingourlay**
## Update 20/02/20

News Web has been kicking goals this past week, and this effort seems more achievable than ever. We're collaborating on some things with a model similar to [react-decoy](https://github.com/colingourlay/react-decoy) and some respectful event signalling, so I'm picking work back up on this project. We've not ironed out all the kinks, but the pace of work is encouraging.

## Update 21/10/19

A recent release of Presentation Layer has made it impossible to view articles which contain components they don't know how to (or don't want to) render, including HTML Fragments (i.e. every enhanced story our team has ever created). They'll now all redirect back to Phase 1. Until we re-gain the capability to see our stories on PL, we can't continue this work, or any other exploratory work around supporting our content on PL (from our end, at least). 🍻

## Original post

This is a bit of preparation work that allows Odyssey to run on top of the current Presentation Layer template output. This may not be the future we all want, but it's likely this will be the future we get. Hey, at least it's not `iframe`s. *Yeeeee-haw!* 🤠

Because Odyssey adds a layer of normalisation to our story output, extending that support to PL allows (most of) our more advanced stories with components like scrollytellers (such as Super K) to also run in a PL-rendered page, because Odyssey gives them a familiar DOM structure to work with.

I've taken care to make sure that (to the best of my knowledge) existing Phase 1/2 support won't be affected by these changes.

#### The Big Caveat (and a temporary workaround)

There's currently no way to run arbitrary JS on PL, so none of this work currently has a deployment / activation strategy, and obtaining such things will require conversations with (and work from) the News Web team. None of these things are guaranteed. I'm just trying to offer up more options for the support of our work on their platform (as the current plan is per-article opt-out of PL, and continued support of Phase 1 that I don't think anybody really wants).

_(\*ignore everything below until we can opt-out of the PL auto-opt-out\*)_

I've been developing this takeover solution with the help of a tiny runtime (similar to news-core's init-interactive loader) that I inject into the page using a bookmarklet. I'll publish the runtime separately at some point, with the hopes that it will eventually replace most of news-core and Phase 2's loader code and give us a unified strategy for news projects going forward (or at least until Phase 1/2 are retired).

For now, you can give it a try yourself...

Drag the bookmarklet on [this page](https://www.abc.net.au/res/sites/news-projects/@abcnews/news-projects-loader/example/runtime.html) to your bookmarks bar, then click it while viewing any of these Presentation Layer-rendered stories:

* [A poison in our island](https://bigted.abc.net.au/news/9161442?proxy_odyssey=phase-3) (a nice example with lots of images/videos inside blocks/galleries)
* [The making of an iceberg](https://bigted.abc.net.au/news/11370748?proxy_odyssey=phase-3) (has an image-pan scrollyteller)
* [Conquering Mount Everest](https://bigted.abc.net.au/news/11162770?proxy_odyssey=phase-3) (has a video scrollyteller)
* [Can you tell a fake video from a real one?](https://bigted.abc.net.au/news/10308638?proxy_odyssey=phase-3) (before & afters, deepfake guessing game)
* [How hard is it to make a believable deepfake?](https://bigted.abc.net.au/news/10313906?proxy_odyssey=phase-3) (before & afters, deepfakes scrollyteller)
* [Super Kamiokande](https://bigted.abc.net.au/news/11209104?proxy_odyssey=phase-3) (has a bunch of complex interactive content)

### CODE REVIEW

**Comment by colingourlay** [comment]
@louisstow here's my skunkworks branch from last year 😂

**Review by drzax — APPROVED** [review]

**Review by phocks — COMMENTED** [review]
Cool

**Comment by katiaeirin** [comment]
Hello! 

A rename from this PR broke a few articles. They are the articles that rely on `window.__ODYSSEY__.utils.anchors.getSections()`and use `section.configSC` which broke after this rename https://github.com/abcnews/odyssey/commit/5c5396bb7257ee611645293d8c31ea517ba32184#diff-7aae5b8f74a04853ba30d657e2b62fa0394cc59aad6995d9711ebbda3017a0dfR334.

I've fixed the articles that I noticed were broken, but worth checking if there are more.

**Comment by drzax** [comment]
That's a good catch — thanks @katiaeirin. 
@colingourlay — maybe for renames in the API we should keep the old one around for a bit and throw a deprecation warning which gets logged somewhere so we can identify any uses?

**Pull request merged**
