### PR TITLE
Gallery and master gallery (+ captions)

### PR DESCRIPTION
**Pull request by jtfell**
I had to make some changes to the caption styling for consistency across mosiac, images, galleries and master galleries.

It's a bit tricky getting all the overrides right, so worth taking a more critical look at the 2nd commit here.

### Note

I also stumbled across a bug? where the caption on the first inline image in this story didn't style the caption with an odyssey component: https://feature-newsweb-articleheadline.news-web-developer.presentation-layer.abc-test.net.au/news/2023-09-23/cybersecurity-troy-hunt-have-i-been-pwned-fighting-data-breaches/102803748?future=true

I suspect it's because its using a custom image but haven't really dug into it yet

### CODE REVIEW

**Comment by jtfell** [comment]
image
image
image

**Comment by jtfell** [comment]
**Mobile:**

image
image

**Desktop:**
image
image
image

**Comment by drzax** [comment]
I'll take a solid look at this on Monday, but just wanted to quickly say that custom images have always been treated differently by Odyssey — they were, I think, left pretty much untouched. They didn't become Picture components. I forget the exact reasoning for this, but it might be important so I'll try to dig out the history on that too.

**Comment by jtfell** [comment]
Yeah, makes sense. We just have to swap out the caption component in future news

**Pull request merged**
